- hosts: standard

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_standard
    oscap_policy: ssg-centos7-ds

  tasks:

  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide

  - block:
    - name: run openscap
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results /tmp/centos-standard.xml \
        --report /tmp/centos-standard.html \
        --fetch-remote-resources
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

    always:

    - name: download report
      fetch:
        src: /tmp/centos-standard.html
        dest: ../oscap-reports/centos-standard.html
        flat: yes

