---
- hosts: c2s
  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_C2S
    oscap_policy: ssg-centos7-ds

  tasks:

    - name: install openscap scanner
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - openscap-scanner
        - scap-security-guide
  
    - name: run openscap
      command: 
        oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results /tmp/centos-c2s.xml \
        --report /tmp/centos-c2s.html \
        --fetch-remote-resources
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

  always:

    - name: download report
      fetch:
        src: /tmp/centos-c2s.html
        dest: ../oscap-reports/centos-c2s.html
        flat: yes

