- hosts: pci-dss

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_pci-dss
    oscap_policy: ssg-centos7-ds

  tasks:

  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - openscap-scanner
    - scap-security-guide

  - block:
    - name: run openscap
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results /tmp/centos-pci-dss.xml \
        --report /tmp/centos-pci-dss.html \
        --fetch-remote-resources \
        /usr/share/xml/scap/ssg/content/{{ oscap_policy }}.xml

    always:

    - name: download report
      fetch:
        src: /tmp/centos-pci-dss.html
        dest: ../oscap-reports/centos-pci-dss.html
        flat: yes
