- hosts: high

  vars:
    oscap_profile: xccdf_org.ssgproject.content_profile_anssi_np_nt28_high
    oscap_policy: ssg-ubuntu1604-ds

  tasks:

  - name: install openscap scanner
    package:
      name: "{{ item }}"
      state: latest
    with_items:
    - libopenscap8

  - block:
    - name: run openscap
      command: oscap xccdf eval \
        --profile {{ oscap_profile }} \
        --results /tmp/ubuntu-high.xml \
        --report /tmp/ubuntu-high.html \
        /home/vagrant/ssg/{{ oscap_policy }}.xml

    always:

    - name: download report
      fetch:
        src: /tmp/ubuntu-high.html
        dest: ../oscap-reports/ubuntu-high.html
        flat: yes
